# Generated by Django 5.1.2 on 2024-10-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('level', models.CharField(max_length=10)),
                ('lecturer_course', models.CharField(max_length=30)),
                ('review_complaint', models.CharField(max_length=100000)),
            ],
        ),
    ]
