# Generated by Django 5.1.2 on 2024-10-15 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='lecturer_course',
            new_name='lecturer_or_course',
        ),
    ]
