# Generated by Django 5.1.2 on 2024-10-15 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_lecturer_course_review_lecturer_or_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_complaint',
            new_name='review_or_complaint',
        ),
    ]
