# Generated by Django 5.1.2 on 2024-10-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_review_or_complaint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='lecturer_or_course',
            new_name='lecturer_name',
        ),
        migrations.AddField(
            model_name='review',
            name='course_code',
            field=models.CharField(default='default_value', max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_or_complaint',
            field=models.TextField(max_length=500),
        ),
    ]
