# Generated by Django 5.1.2 on 2024-10-23 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
